### ISSUE TITLE
Recommendation method 

### ISSUE THREAD

**Issue by subeans** [kookmin-sw/capstone-2021-15#24]
우리 추천시스템에 적용가능한 recommendation method 가 무엇이 있는지 알아보고 예시 코드 돌리며 이해하기

**Comment by minjeongnew** [comment]
gru4rec 코드 customize 진행
buydata 를 통해 similarity 계산
run.sh -> 실험 진행
feedback.py -> feedback db에서 읽어와서 비율 계산
rewards.py -> 모델을 사용해서 추출된 아이템에 score 부여
